export const actionTypes = {
    initialValue: "initialValue",
    sae1_started: "sae1_started",
    sae2_started: "sae2_started",
    sae3_started: "sae2_started",
    sa_bonus_started: "sa_bonus_started",
    sae1_completed: "sae1_completed",
    sae2_completed: "sae2_completed",
    sae3_completed: "sae3_completed",
    sbe1_started: "sbe1_started",
    sbe2_started: "sbe2_started",
    sbe3_started: "sbe2_started",
    sb_bonus_started: "sb_bonus_started",
    sbe1_completed: "sbe1_completed",
    sbe2_completed: "sbe2_completed",
    sbe3_completed: "sbe3_completed",
    sa_completed: "sa_completed",
    sb_completed: "sb_completed",
    sa_bonus_completed: "sa_bonus_completed",
    p1_completed: "p1_completed",
    p2_completed: "p2_completed",
    p3_completed: "p3_completed",
    p4_completed: "p4_completed",
    p5_completed: "p5_completed",
    p6_completed: "p6_completed",
     
}